name: Deploy to Staging
on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster
    steps:
      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@54.215.126.102 << 'EOF'
            cd w-25-2/
            git pull origin main
            export PATH=$HOME/.nvm/versions/node/v22.13.1/bin:$PATH
            source ~/.nvm/nvm.sh
            npm install -g pnpm
            pnpm install
            pnpm run build
            pm2 restart all
          EOF
